# Generated by Django 2.2.4 on 2019-08-26 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=250)),
                ('company', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=50)),
                ('user_interest_rating', models.IntegerField(choices=[('low', 1), ('medium', 2), ('high', 3)], default=3)),
                ('user_prospect_rating', models.CharField(choices=[('s', 'safety'), ('b', 'ballpark'), ('r', 'reach')], max_length=1)),
                ('img_url', models.URLField(max_length=250)),
            ],
        ),
    ]
