# Generated by Django 2.2.4 on 2019-08-26 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='user_interest_rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=3),
        ),
        migrations.AlterField(
            model_name='job',
            name='user_prospect_rating',
            field=models.CharField(choices=[('safety', 'safety'), ('ballpark', 'ballpark'), ('reach', 'reach')], max_length=1),
        ),
    ]
